### PR TITLE
package & access assets correctly

### PR DESCRIPTION
**Pull request by cburgard**
Right now, the .jar created by the gradle.build file does not package the assets in a way that can be accessed by the app.

This PR contains some developments to try and alleviate this shortcoming.

### CODE REVIEW

**Comment by cburgard** [comment]
@jeheydorn : what's the idea about how the assets are handled?
looking at the script that makes the ubuntu installer, it seems like there is some "isInstalled" flag in AssetsPath, which I don't quite understand how it's supposed to work...

**Comment by jeheydorn** [comment]
Ah, I responded in another thread.

**Comment by cburgard** [comment]
@jeheydorn I hope this should work now, please let me know if you have any issues. If not, feel free to merge!

**Comment by jeheydorn** [comment]
I commend you in your efforts to refactor this much, but there's a few things I need to point out.

Did you see what I added in the conversation that [?]( https://github.com/jeheydorn/nortantis/pull/23) I'm new to using GitHub to collaborate, so I'm not sure if you see my replies to conversations in a closed pull request. My reply there might change the direction you want to go with this change.

Aside from the issues I pointed out in that conversation, I have some concerns from briefly looking at your changes.

In Background.java:

Regarding this change:
image

readImageFromAssets it's not a suitable replacement for calls into ImageCache.getImageFromFile because you lose the caching (unless readImageFromAssets does its own caching). Caching is essential for performance when the map re-draws. But I think the better solution would be to move the caching into ImageCache so we do the caching in only one place.

Regarding this change:
image
Why did you take out the error handling when the background image doesn't exist? This case could still be hit if using a custom images folder (accessed through the edit menu in Nortantis). It looks like you've taken out error messages like that in other places too.

Regarding this:
image
This isn't going to work if the background image isn't from the assets. The UI allows selecting any image file on disk.

In AwtFactory.readImage, your change assumes the image is coming from the resources (assets) (unless getClass().getClassLoader().getResourceAsStream(filePath) can read files from disk that aren't resources). So this won't work for maps with custom images folders. 

In build.gradle, if feels odd to hardcode Background.java here:
// Define a task to format a specific file
task formatSpecificFile {
    doLast {
        def filePath = project.hasProperty('filePath') ? project.filePath : 'src/nortantis/Background.java'
        println "Formatting file: $filePath"
        javaexec {
            main = 'com.diffplug.spotless.Main'
            classpath = configurations.spotless
            args 'apply', '--java', filePath
        }
    }
}
Just a coding style thing. Could you let the task error out if you don't supply a file?

I checked out your branch and imported it into eclipse. When I try to run MainWindow.java, I get this error popup:
image

When I ran gradle build, I got this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessJavaCheck'.
> The following files had format violations:
      src\nortantis\Biome.java
          @@ -16,14 +16,11 @@
           \tÂ·*/
           
           \tOCEAN(0x44447a),Â·LAKE(0x336699),Â·BEACH(0xa09077),Â·SNOW(0xffffff),Â·TUNDRA(0xbbbbaa),Â·BARE(0x888888),Â·SCORCHED(0x555555),Â·TAIGA(
          -\t\t\t0x99aa77
          -\t),Â·SHURBLAND(0x889977),Â·TEMPERATE_DESERT(0xc9d29b),Â·HIGH_TEMPERATE_DESERT(0xbdc499),Â·TEMPERATE_RAIN_FOREST(
          -\t\t\t0x448855
          -\t),Â·TEMPERATE_DECIDUOUS_FOREST(0x679459),Â·HIGH_TEMPERATE_DECIDUOUS_FOREST(0x4a773d),Â·GRASSLAND(0x88aa55),Â·SUBTROPICAL_DESERT(
          -\t\t\t0xd2b98b
          -\t),Â·SHRUBLAND(0x889977),Â·ICE(
          -\t\t\t0x99ffff
          -\t),Â·MARSH(0x2f6666),Â·TROPICAL_RAIN_FOREST(0x337755),Â·TROPICAL_SEASONAL_FOREST(0x559944),Â·COAST(0x33335a),Â·LAKESHORE(0x225588);
          +\t\t\t0x99aa77),Â·SHURBLAND(0x889977),Â·TEMPERATE_DESERT(0xc9d29b),Â·HIGH_TEMPERATE_DESERT(0xbdc499),Â·TEMPERATE_RAIN_FOREST(
          +\t\t\t\t\t0x448855),Â·TEMPERATE_DECIDUOUS_FOREST(0x679459),Â·HIGH_TEMPERATE_DECIDUOUS_FOREST(0x4a773d),Â·GRASSLAND(
          +\t\t\t\t\t\t\t0x88aa55),Â·SUBTROPICAL_DESERT(0xd2b98b),Â·SHRUBLAND(0x889977),Â·ICE(
          +\t\t\t\t\t\t\t\t\t0x99ffff),Â·MARSH(0x2f6666),Â·TROPICAL_RAIN_FOREST(
          +\t\t\t\t\t\t\t\t\t\t\t0x337755),Â·TROPICAL_SEASONAL_FOREST(0x559944),Â·COAST(0x33335a),Â·LAKESHORE(0x225588);
           
           \tColorÂ·color;
           
      src\nortantis\CharacterNGram.java
          @@ -126,8 +126,7 @@
           \t\t\t{
           \t\t\t\tresultÂ·+=Â·next;
           \t\t\t}
          -\t\t}
          -\t\twhileÂ·(nextÂ·!=Â·endToken);
          +\t\t}Â·whileÂ·(nextÂ·!=Â·endToken);
           
           \t\treturnÂ·result;
           \t}
      src\nortantis\DebugFlags.java
          @@ -3,41 +3,41 @@
           importÂ·nortantis.util.AssetsPath;
           
           publicÂ·classÂ·DebugFlags
          -{\t
          +{
           \t/**
           \tÂ·*Â·CausesÂ·theÂ·replacementÂ·drawÂ·boundsÂ·forÂ·incrementalÂ·updatesÂ·toÂ·beÂ·drawnÂ·ontoÂ·theÂ·map.
           \tÂ·*/
           \tprivateÂ·staticÂ·booleanÂ·showIncrementalUpdateBoundsÂ·=Â·false;
          -\t
          +
           \t/**
           \tÂ·*Â·PrintsÂ·howÂ·longÂ·incrementalÂ·updatesÂ·take.
           \tÂ·*/
           \tprivateÂ·staticÂ·booleanÂ·printIncrementalUpdateTimesÂ·=Â·false;
           
      ... (79 more lines that didn't fit)
  Violations also present in 93 other files.
```

Is spottless something we need? I prefer to use eclipse for code formatting, and I don't want to have to manage settings in two different tools for that. Is there a way to make it so that you can use spotless, but others don't have to run it when I build with gradle? If I don't use spotless, it will cause build errors like this when other people build with gradle.

Let me know if the images I pasted in above don't show up. This is my first time to try doing so.

**Comment by cburgard** [comment]
Hi!

Thanks for your detailed replies.

I already anticipated there would be a wealth of issues, but I just wanted to have a go at it anyway just to get an overview over all the places that need changing. I'll reply to your comments individually, 

- Caching: I was unaware of any caching going on, and my java knowledge is not sufficient to understand what's going on, I'm more on a monkey-see-monkey-do basis here. Feel free to mess with the code I put in to reinstate the caching or start from scratch, but I'm not sure I would even understand where to start with this.
- File paths: It seems there's this ongoing theme of wanting to make it possible for users to supply their own inputs instead of using the assets, which is a great feature of course that I wasn't even aware of. Perhaps the sanest solution here would be to just pass down a flag from the GUI to see if the file was user-selected (in which case one would load it from the file system) or if it's internal (in which case it's loaded from the JAR). Or would you see any issues with this? For example, I don't know if it's a use case to have users navigate the files in the JAR to select some of those, which would break this idea. But from what I could see so far, the files in the JAR are more provided as checkmark-lists (such as the books, for example) or perhaps dropdown menus?
- Gradle / spotless: I mostly added this because I wanted to make sure that the code I add follows your coding convention. I agree that the explicit usage of Background.java here is ugly, but I didn't know how else to handle the case of no argument being given. I'm not using eclipse (or any GUI editor), I'm more of an "emacs -nw" guy, so I wanted some way to auto-format the code. Feel free to roll back this part, but are you aware of any command line tool that can be used for formatting the code in the way you want? I tried the google-java-formatter, but the format of that seems to be quite different from what you normally do, and it's also not very configurable. I also tried eclipse headless, but I'm not able to make that respect the settings I put in the xml, so I wouldn't know how to move on from here. Preferably, I would like to be able to run spotless (or any other formatter, really) only via specific command line and only on specific files (such as to reformat the files I messed with before committing). That it runs all of the time by default now is more of an accident that I don't know how to get rid of.

By the way, no worries about the response times, this is a leisure project after all :) 
I'll be away from the internet for about 10 days starting today, but I might pick up from where I left off (or whatever you propose as a good starting point / strategy) after.

Thanks for you quick and comprehensive review!

**Comment by jeheydorn** [comment]
I'll give two thumbs up to not worrying about response times :) I just do
this project for fun, and it has the added benefit of giving me maps for
the books I'm writing.

Caching:
All the caching I do is inside of ImageCache. ImageCache contains one
static instance per images folder, using this static variable:
private static HashMapF<String, ImageCache> instances = new HashMapF<>();

Before your changes, one of the images folders in the keyset of that map
was the assets folder. The other keys, if present, would be custom images
folders for maps. Usually there are most two keys in that map, but in rare
cases you could have more than one custom images folder with a key in
ImagesCache, such as if you open a map with a custom images folder, then
create a new map with a different custom images folder, and haven't closed
the new map dialogue yet.

I'm fine making your change work for ImagesCache if you don't want to mess
with this.

File paths:
Yes, any of the icons or borders on the map could come from a custom images
folder. It's an override that allows users to use their own images. You are
correct that there is no use case for users navigating through the packaged
resources in the assets folder to select files. Currently users can select
background textures in the assets folder, which is probably the only place
that allows them to navigate the assets folder, but that's going to have to
change for this change to work (and I'm fine developing that myself if you
want; I was thinking of doing it anyways when I create installable
art-packs). The change for background texture images would, for now, be to
change the file selector to a dropdown, plus have an option to select a
file from anywhere on disk with the file selector in case someone wants to
use their own texture. And we would need a conversion for existing maps to
select the correct dropdown option if they use one of the built in
background textures.

Passing a flag to everywhere that ImageCache needs to load files to tell
whether they're coming from resources is one option, but I think we might
be able to get away with simply checking if the path starts with a folder
named "assets". In theory that assumption would be broken if someone used a
relative path that starts with an "assets" folder, but the UI doesn't allow
relative paths for either custom images folders or background textures, so
it shouldn't be an issue.

Gradle / spotless:
I didn't realize it uses my eclipse preferences. In that case, it's fine.

**Comment by jeheydorn** [comment]
I've integrated this change into my master branch, although I ended up doing a lot of rewriting to support this with loading icons, borders, and background textures from the assets folder or from custom images folders, or from a new feature: art packs. So now if you run from source, Nortantis will still pull from the assets folder, but if you run from a jar file, it will pull assets from the jar file. The logic for doing this switching is in Assets.java.

**Pull request closed without merging**
